call pathogen#infect()

filetype plugin on
" filetype plugin indent on

set tabstop=2
set expandtab
syn on
set hls
set nu
set cursorline
set showtabline=2
set textwidth=80
set ml
set t_Co=256

let g:tagbar_type_coffee = {
      \ 'ctagstype' : 'coffee',
      \ 'kinds' : [
      \   'c:classes',
      \   'f:functions',
      \   'v:variables'
      \ ],
      \ }

nmap ,, :tabnew<CR>
nmap ,. :tabnext<CR>
nmap ., :tabpre<CR>

map <leader>t :FufFile<CR>


set wildmode=list:longest
set shortmess=atI
set mouse=a
set laststatus=2
match ErrorMsg '\%>80v.\+'

set rtp+=$GOROOT/misc/vim
set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim

colorscheme molokai
